@echo off
setlocal
chcp 65001 >nul

rem ============================================================
rem  Build PC version into a single-file exe (PyInstaller)
rem
rem  The exe name is generated by pc\build_exe.py
rem  Output: Desktop\StockScreener_<timestamp>.exe
rem ============================================================

set "PY="

echo.
echo === Stock Screener - PC build ===
echo.

rem ---- locate Python ----
where python >nul 2>nul
if %errorlevel%==0 set "PY=python"
if defined PY goto py_ok

if exist "D:\Anaconda\python.exe" set "PY=D:\Anaconda\python.exe"
if defined PY goto py_ok

echo.
echo [ERROR] Python not found. Install Python 3.8+ and add it to PATH.
goto done

:py_ok
echo [PYTHON] %PY%

rem ---- check PyInstaller ----
%PY% -c "import PyInstaller" >nul 2>nul
if %errorlevel%==0 goto have_pyinstaller

echo [INFO] PyInstaller not found, installing...
%PY% -m pip install pyinstaller
if not %errorlevel%==0 goto pip_fail

:have_pyinstaller

rem ---- build ----
cd /d "%~dp0pc"
%PY% build_exe.py
if not %errorlevel%==0 goto build_fail

echo.
echo [OK] exe written to Desktop.
goto done

:pip_fail
echo.
echo [ERROR] Failed to install PyInstaller. Check network / pip config.
goto done

:build_fail
echo.
echo [FAILED] Build did not pass. Check the output above.
goto done

:done
echo.
pause
endlocal
